set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports LD2]
set_property IOSTANDARD LVCMOS33 [get_ports LD3]
set_property IOSTANDARD LVCMOS25 [get_ports reset]
set_property SLEW SLOW [get_ports LD2]
set_property SLEW SLOW [get_ports LD3]
set_property PACKAGE_PIN U22 [get_ports LD2]
set_property PACKAGE_PIN U21 [get_ports LD3]
set_property PACKAGE_PIN P16 [get_ports reset]

set_property OFFCHIP_TERM NONE [get_ports LD2]
set_property OFFCHIP_TERM NONE [get_ports LD3]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]
