set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T22 [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property SLEW SLOW [get_ports LD0]
set_property PACKAGE_PIN R16 [get_ports reset]
set_property IOSTANDARD LVCMOS25 [get_ports reset]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]


set_property OFFCHIP_TERM NONE [get_ports LD0]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[6]]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[5]]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[4]]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[3]]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[2]]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[1]]
set_property OFFCHIP_TERM NONE [get_ports LED_7_1_tri_o[0]]
set_property PACKAGE_PIN T21 [get_ports {LED_7_1_tri_o[0]}]
set_property PACKAGE_PIN U22 [get_ports {LED_7_1_tri_o[1]}]
set_property PACKAGE_PIN U21 [get_ports {LED_7_1_tri_o[2]}]
set_property PACKAGE_PIN V22 [get_ports {LED_7_1_tri_o[3]}]
set_property PACKAGE_PIN W22 [get_ports {LED_7_1_tri_o[4]}]
set_property PACKAGE_PIN U19 [get_ports {LED_7_1_tri_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED_7_1_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_7_1_tri_o[6]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[6]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[5]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[4]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[3]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[2]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[1]}]
set_property SLEW SLOW [get_ports {LED_7_1_tri_o[0]}]
set_property PACKAGE_PIN N15 [get_ports {BUTTON_tri_i[0]}]
set_property PACKAGE_PIN R18 [get_ports {BUTTON_tri_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {BUTTON_tri_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {BUTTON_tri_i[0]}]
